services:

  postgres:
    image: postgres:15
    container_name: knowledge-hub-postgres
    restart: always
    environment:
      POSTGRES_DB: knowledge_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: knowledge-hub-postgres-test
    restart: always
    environment:
      POSTGRES_DB: knowledge_hub_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: knowledgehub-redis
    ports:
      - "6379:6379"
    restart: always
    
volumes:
  postgres_data:
  postgres_test_data: